server:
  port: 8080
spring:
  kafka:
    ssl:
      key-password: admin123
      keystore-location: client.keystore.jks
      keystore-password: admin123
      truststore-location: client.truststore.jks
      truststore-password: admin123
    consumer:
      bootstrap-servers: my-cluster-kafka-brokers:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer